[package]
name = "rust-fundamentals"
version = "0.1.0"
authors = ["shinobi5"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
